use_frameworks!

platform :ios, '9.0'

target 'WkBridgeSwift_Example' do
  pod 'SnapKit', '~> 4.2.0'
#  pod 'WkBridgeSwift'
  pod 'WkBridgeSwift', :path => '../'

  target 'WkBridgeSwift_Tests' do
    inherit! :search_paths

    
  end
end
